
package com.znv.manage.webservice;

import javax.xml.namespace.QName;
import javax.xml.ws.*;
import java.net.MalformedURLException;
import java.net.URL;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SmcExternal2", targetNamespace = "http://smc.huawei.com/", wsdlLocation = "https://smc.tp.huawei.com/ws/Smcexternal2.asmx?wsdl")
public class SmcExternal2
    extends Service
{

    private final static URL SMCEXTERNAL2_WSDL_LOCATION;
    private final static WebServiceException SMCEXTERNAL2_EXCEPTION;
    private final static QName SMCEXTERNAL2_QNAME = new QName("http://smc.huawei.com/", "SmcExternal2");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://smc.tp.huawei.com/ws/Smcexternal2.asmx?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SMCEXTERNAL2_WSDL_LOCATION = url;
        SMCEXTERNAL2_EXCEPTION = e;
    }

    public SmcExternal2() {
        super(__getWsdlLocation(), SMCEXTERNAL2_QNAME);
    }

    public SmcExternal2(WebServiceFeature... features) {
        super(__getWsdlLocation(), SMCEXTERNAL2_QNAME, features);
    }

    public SmcExternal2(URL wsdlLocation) {
        super(wsdlLocation, SMCEXTERNAL2_QNAME);
    }

    public SmcExternal2(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SMCEXTERNAL2_QNAME, features);
    }

    public SmcExternal2(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SmcExternal2(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SmcExternal2Soap
     */
    @WebEndpoint(name = "SmcExternal2Soap")
    public SmcExternal2Soap getSmcExternal2Soap() {
        return super.getPort(new QName("http://smc.huawei.com/", "SmcExternal2Soap"), SmcExternal2Soap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SmcExternal2Soap
     */
    @WebEndpoint(name = "SmcExternal2Soap")
    public SmcExternal2Soap getSmcExternal2Soap(WebServiceFeature... features) {
        return super.getPort(new QName("http://smc.huawei.com/", "SmcExternal2Soap"), SmcExternal2Soap.class, features);
    }

    /**
     * 
     * @return
     *     returns SmcExternal2Soap
     */
    @WebEndpoint(name = "SmcExternal2Soap12")
    public SmcExternal2Soap getSmcExternal2Soap12() {
        return super.getPort(new QName("http://smc.huawei.com/", "SmcExternal2Soap12"), SmcExternal2Soap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SmcExternal2Soap
     */
    @WebEndpoint(name = "SmcExternal2Soap12")
    public SmcExternal2Soap getSmcExternal2Soap12(WebServiceFeature... features) {
        return super.getPort(new QName("http://smc.huawei.com/", "SmcExternal2Soap12"), SmcExternal2Soap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SMCEXTERNAL2_EXCEPTION!= null) {
            throw SMCEXTERNAL2_EXCEPTION;
        }
        return SMCEXTERNAL2_WSDL_LOCATION;
    }

}
