thrid:
  config:
    ## 里约网关鉴权信息
    paasid: wxbhwmcs
    paasToken: 2b4a213f6a6be0585999d89a20c1d6c6
    ## 客户端的ID和秘钥
    appId: D45Etrjz
    appSecret: d9c20de5ba68944fbba42098c9d8513697bbd7fd
    ## 客户端大屏的ID和秘钥
    screenAppId: MAy42y5g
    screenAppSecret: 2c1b08257ba3c3b6022f2dc426b478a68884a970
    ## 使用的授权模式
    grantType: authorization_code
    ## 申请的权限范围
    scope: all
    ## 授权类型，必选项，此处的值固定为"code"
    responseType: code
    ## 重定向URI
    redirectUri: http://2.21.137.224:8080/autologin
    screenRedirectUri: http://2.21.137.224:8080/wmcs/
    ## 数据同步地址
    dataSynchUrl: http://2.22.51.26:30000/ebus/wxbhtysf
    ## 单点登录api地址
    oauthApiUrl: http://2.22.51.26:30002
    ## 单点登陆授权跳转地址
    authorizationUrl: http://2.22.51.26:30002

wmb:
  ip: http://2.22.51.26:30000/ebus/wxbhsjz/qxcb/
  username: Ymhx
  password: YmhxNjY2ODg4

ai:
  count: 300
  ip: 2.21.138.49
  secretId: a40c373844364e69b646100a49
  secretKey: acd182953fd64cf0ba01a87de0
  gatewayUrl: http://2.21.138.49/gateway
  imageDownloadUrl: http://2.21.138.49/


event:
  config:
    enable: true
    # addr: http://2.21.137.154:88
    addr: http://192.250.161.26:88
    name: wmcs
    password: MTIzNDU2
    # eventUrl: http://2.21.137.154:9527
    eventUrl: http://192.250.161.26:88
    minioUrl: http://192.170.13.96:9001/wmcs/

video:
  config:
    # addr: http://2.20.28.22:8314
    addr: https://2.20.28.22:7902
    clientType: winpc
    userName: wmcscj
    password: wmcscj@123456

wechat:
  config:
    agentId: 1000428
    corpid: ww29a8dfb1be6173c1
    corpsecret: mZSVG4FUb44D1K-ljxU1Ms8L0nfm4xrOAVRi0aeD_lc
    addr: https://2.20.105.11:10443
    url: http://2.21.137.224:8080/wechat/
