## 数据源配置
#spring:
#    datasource:
#        type: com.alibaba.druid.pool.DruidDataSource
#        driverClassName: org.postgresql.Driver
#        druid:
#            # 主库数据源
#            master:
#                #服务器
#                url: jdbc:postgresql://2.21.137.206:5432/ocn_system?useSSL=false
#                #本地
##                url: jdbc:postgresql://10.10.29.236:5432/bin_hu?useSSL=false
#                username: postgres
#                password: O.cnwx123
#            # 从库数据源
#            slave:
#                # 从数据源开关/默认关闭
#                enabled: false
#                url:
#                username:
#                password:
#            # 初始连接数
#            initialSize: 5
#            # 最小连接池数量
#            minIdle: 10
#            # 最大连接池数量
#            maxActive: 20
#            # 配置获取连接等待超时的时间
#            maxWait: 60000
#            # 配置连接超时时间
#            connectTimeout: 30000
#            # 配置网络超时时间
#            socketTimeout: 60000
#            # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
#            timeBetweenEvictionRunsMillis: 60000
#            # 配置一个连接在池中最小生存的时间，单位是毫秒
#            minEvictableIdleTimeMillis: 300000
#            # 配置一个连接在池中最大生存的时间，单位是毫秒
#            maxEvictableIdleTimeMillis: 900000
#            # 配置检测连接是否有效
#            validationQuery: SELECT 1
#            testWhileIdle: true
#            testOnBorrow: false
#            testOnReturn: false
#            webStatFilter:
#                enabled: true
#            statViewServlet:
#                enabled: true
#                # 设置白名单，不填则允许所有访问
#                allow:
#                url-pattern: /druid/*
#                # 控制台管理用户名和密码
#                login-username: ruoyi
#                login-password: 123456
#            filter:
#                stat:
#                    enabled: true
#                    # 慢SQL记录
#                    log-slow-sql: true
#                    slow-sql-millis: 1000
#                    merge-sql: true
#                wall:
#                    config:
#                        multi-statement-allow: true


# 数据源配置
spring:
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
#        driverClassName: org.postgresql.Driver
        druid:
            # 主库数据源
            master:
                #服务器
                url: jdbc:postgresql://2.21.137.206:5432/ocn_system?useSSL=false
                #本地
#                url: jdbc:postgresql://10.10.29.236:5432/bin_hu?useSSL=false
                username: postgres
                password: O.cnwx123
            # 从库数据源
            slave:
                enabled: true
                #服务器
                url: jdbc:mysql://2.22.51.16:9030/stg_qgaj?useSSL=false
                username: collect_jjydn
                password: bhq@jjydn
#                #本地
#                url: jdbc:mysql://10.10.20.122:3306/scm_cc?useSSL=false
#                username: root
#                password: root
#                url: jdbc:postgresql://10.10.29.236:5432/bin_hu?useSSL=false
#                username: postgres
#                password: O.cnwx123
            # 初始连接数
            initialSize: 5
            # 最小连接池数量
            minIdle: 10
            # 最大连接池数量
            maxActive: 20
            # 配置获取连接等待超时的时间
            maxWait: 60000
            # 配置连接超时时间
            connectTimeout: 30000
            # 配置网络超时时间
            socketTimeout: 60000
            # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
            timeBetweenEvictionRunsMillis: 60000
            # 配置一个连接在池中最小生存的时间，单位是毫秒
            minEvictableIdleTimeMillis: 300000
            # 配置一个连接在池中最大生存的时间，单位是毫秒
            maxEvictableIdleTimeMillis: 900000
            # 配置检测连接是否有效
            validationQuery: SELECT 1
            testWhileIdle: true
            testOnBorrow: false
            testOnReturn: false
            webStatFilter:
                enabled: true
            statViewServlet:
                enabled: true
                # 设置白名单，不填则允许所有访问
                allow:
                url-pattern: /druid/*
                # 控制台管理用户名和密码
                login-username: ruoyi
                login-password: 123456
            filter:
                stat:
                    enabled: true
                    # 慢SQL记录
                    log-slow-sql: true
                    slow-sql-millis: 1000
                    merge-sql: true
                wall:
                    config:
                        multi-statement-allow: true
